title: Informática IFRN
email:
description: "Projeto para o hacktoberfest"
baseurl: ""
url: "arenullb.github.io"
twitter_username:
github_username:

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - members
